config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks

  validates_presence_of :name
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates_presence_of :description

  def toggle_completed!
    update(completed: !completed)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
    @task = Task.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

    def list_params
      params.require(:list).permit(:name)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.new(task_params)
    @task.completed = false
    @task.list = List.find(params[:list_id])

    if @task.save
      redirect_to list_path(@task.list.id)
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.toggle_completed!

    redirect_to list_path(@task.list.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @list = @task.list
    @task.destroy

    redirect_to list_path(@list)
  end

  private

    def task_params
      params.require(:task).permit(:description, :completed, :list_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
 
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name, 'Task' %>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :complete, 'Completed?' %>
    <%= f.check_box :complete %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/tasks/_task.html.erb
<li class="<%= 'completed' if task.completed %>">
  <%= task.description %>
  <% if task.completed %>
    <%= link_to "Mark incomplete", list_task_path(task.list_id, task.id), method: :put %>
  <% else %>
    <%= link_to "Complete", list_task_path(task.list_id, task.id), method: :put %>
  <% end %>
  <%= link_to "Remove", list_task_path(task.list_id, task.id), method: :delete %>
</li>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<%= render 'form' %> 
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<div id="task-list" style="width: 300px; border-bottom: 1px solid black">
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <p>[<%= task.complete ? "x" : " " %>] <%= task.name %></p>

        <%= form_tag task, params: {id: task.id}, method: :patch do %>
          <%= submit_tag("Mark Complete") %>
        <% end %>

        <%= form_tag task, params: {id: task.id}, method: :delete do %>
          <%= submit_tag("Delete") %>
        <% end %>
        
      </li>
    <% end %>
  </ul>
</div>
<div>
  <h1>Create a new task</h1>
  <%= form_for @task do |f| %>
    <p>
      <%= f.label "Describe your task" %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label "Completed?" %>
      <%= f.check_box :complete %>
    </p>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @task.name %>
</p>
<p>
    <strong>Complete:</strong>
    <%= @task.complete %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>