TasksApp/config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root 'tasks#index'

end

TasksApp/app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true,
                          length:   { minimum: 2, maximum: 100 }
end

TasksApp/app/controllers/tasks_controller.rb
require 'pry'

class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to @task }
      end
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :completed)
  end
end

TasksApp/app/views/tasks/_form.html.haml
.row
  .col-md-5.col-sm-8.col-xs-12
    = form_for @task do |f|
      - if @task.errors.any?
        .panel.panel-danger
          .panel-heading#error_explanation
            = "#{pluralize(@task.errors.count, 'error')} prohibited this task from being saved:"
          %ul
            - @task.errors.full_messages.each do |msg|
              %li= msg

      .form-group
        = f.label 'Task description', for: "description"
        = f.text_field :description, class: "form-control"
     
      .form-group
        = f.label 'Completed'
        = f.check_box :completed
     
      = f.submit "Submit", class: 'btn btn-success'

TasksApp/app/views/tasks/edit.html.haml
%h1 Edit task

= render 'form'

= link_to tasks_path, title: "Back to task list" do
  %i.glyphicon.glyphicon-arrow-left

TasksApp/app/views/tasks/index.html.haml
.row
  .col-md-8.col-xs-12.center-block

    .panel.panel-primary
      .panel-heading
        All Tasks

      %table.table
        %tr
          %th Description
          %th.completed-column Completed
          %th.icon
          %th.icon
       
        - @tasks.each do |task|
          %tr
            %td= task.description
            %td.completed-column
              - if task.completed
                %i{class: 'glyphicon glyphicon-ok completed'}
              - else
                %i{class: 'glyphicon glyphicon-ok not-completed'}
            %td.icon
              = link_to edit_task_path(task) do
                %i.glyphicon.glyphicon-pencil

            %td.icon
              = link_to task_path(task), method: :delete, data: { confirm: 'Are you sure?' } do
                %i.glyphicon.glyphicon-trash

TasksApp/app/views/tasks/new.html.haml
%h1 Create a new task

= render 'form'

= link_to tasks_path, title: "Back to task list" do
  %i.glyphicon.glyphicon-arrow-left

TasksApp/app/views/tasks/show.html.haml
.row
  .col-md-8.col-xs-12.center-block

    .panel.panel-success
      .panel-heading
        Task:

      %table.table
        %tr
          %th Description
          %th.completed-column Completed
          %th.icon
       
        %tr
          %td= @task.description
          %td.completed-column
            - if @task.completed
              %i{class: 'glyphicon glyphicon-ok completed'}
            - else
              %i{class: 'glyphicon glyphicon-ok not-completed'}
          %td.icon
            = link_to edit_task_path(@task) do
              %i.glyphicon.glyphicon-pencil